# Site settings
title: MiaoMiao.io
SEOTitle: Peter's Blog | MiaoMiao.io
header-img: img/home-bg.jpg
email: peterpee@vip.qq.com
description: 
keyword: 
url: miaomiao.io            # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     
zhihu_username:     hao-wen-pi
github_username:    uiuu123
#twitter_username:   huxpro
facebook_username:  phw1998
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: false

# Netease setttings
netease_comment: false

livere_uid: MTAyMC8zMzUzMS8xMDA4Nw==


# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-112996267-1'            # Format: UA-xxxxxx-xx
ga_domain: miaomiao.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一张猫饼，我是小橘<br>和你分享技术、财经、文化与政治"
sidebar-avatar: /img/maobing.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
